---
schema: olm.composite.catalogs
catalogs:
  - name: "v4.12"
    destination:
      baseImage: quay.io/operator-framework/opm:v1.29
      workingDir: .
    builders:
      - olm.builder.basic
  - name: "v4.13"
    destination:
      baseImage: quay.io/operator-framework/opm:v1.29
      workingDir: .
    builders:
      - olm.builder.basic
